### PR TITLE
Update IDR Redmine

### PR DESCRIPTION
**Pull request by manics**
Some major changes as redmine moves towards production. Includes:
- Look and feel changes
- Redmine customisations (additional plugins and patches)
- Custom docker image included in this repo
- More setup instructions for day-to-day tasks
- Switch to Helm chart (this makes configuration easier)

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
At a high-level, these changes look:

 * good
 * nicely templated
 * thorough (in terms of capturing everything need for the install).

I'm unclear whether or not I would be able to run this in a staging manner. If that's something that should be doable, I can give a try ASAP.

(NB: I was slightly surprised by the embedded `docker/Dockerfile` but certainly not a blocker)

**Comment by manics** [comment]
It should be possible to set this up as a staging deployment by creating database and mail credentials, and changing the ingress hostname/prefix. I haven't tried it. Longer term it would make sense to have some staging configuration overrides in https://github.com/openmicroscopy/kubernetes-apps and a separate staging k8s cluster

**Comment by manics** [comment]
The embedded Dockerfile is to avoid yet-another repo. I can separate it out if you prefer- probably easiest if you create an empty repo to avoid travis problems.

**Comment by joshmoore** [comment]
Happy to keep things as they are, but something to be aware of in terms of finding things.

**Pull request merged**
